---
apiVersion: v1
kind: Namespace
metadata:
  name: username
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-clusterslice
  namespace: username
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clusterslice-user-username
  namespace: username
rules:
- apiGroups:
  - swn.uom.gr
  resources:
  - slicerequests
  - multiclusterslicerequests
  verbs: ["get", "list", "create", "delete"]
- apiGroups:
  - swn.uom.gr
  resources:
  - slices
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clusterslice-user-username-monitor-binding
  namespace: swn
roleRef:
  kind: Role
  name: clusterslice-user-monitor
  apiGroup: ""
subjects:
- kind: User
  name: username
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clusterslice-user-username-binding
  namespace: username
roleRef:
  kind: Role
  name: clusterslice-user-username
  apiGroup: ""
subjects:
- kind: User
  name: username
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-clusterslice
  namespace: username
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitor-clusterslice
subjects:
- kind: ServiceAccount
  name: monitor-clusterslice
  namespace: swn
- kind: ServiceAccount
  name: monitor-clusterslice
  namespace: username
