---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-clusterslice
  namespace: swn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-clusterslice
rules:
- apiGroups:
  - swn.uom.gr
  resources:
  - computeresources
  - slices
  - slicerequests
  - multiclusterslicerequests
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "pods/exec","secrets"]
  verbs: ["get", "list", "delete", "patch", "create", "watch"]
    #- apiGroups: ["batch"]
    #resources: ["jobs"]
    #verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clusterslice-user-monitor
  namespace: swn
rules:
- apiGroups:
  - swn.uom.gr
  resources:
  - computeresources
  verbs: ["list"]
