apiVersion: "swn.uom.gr/v1"
kind: MultiClusterSliceRequest
metadata:
  name: plain
  namespace: swn
spec:
  name: plain
  usernamespace: swn
  deploymentstrategy: balanced
  credentials:
    username: clusterslice
    password: sha-512-encoded-password
  clusters:
    - name: plain1
      deploymentdomain: swntestbed
      infrastructure:
        masters:
          count: 1
          osimage: "ubuntu-22-clean"
          mastertype: "vm"
        workers:
          count: 1
          osimage: "ubuntu-22-clean"
          workertype: "vm"
    - name: plain2
      deploymentdomain: lefteris
      infrastructure:
        masters:
          count: 1
          osimage: "ubuntu-22-clean"
          mastertype: "vm"
        workers:
          count: 1
          osimage: "ubuntu-22-clean"
          workertype: "vm"
