apiVersion: "swn.uom.gr/v1"
kind: SliceRequest
metadata:
  name: plainslice
  namespace: swn
spec:
  name: plainslice
  usernamespace: swn
  deploymentstrategy: balanced
  deploymentdomain: swntestbed
  credentials:
    username: clusterslice
    password: sha-512-encoded-password
  infrastructure:
    masters:
      count: 1
      osimage: "ubuntu-22-clean"
      mastertype: "vm"
    workers:
      count: 2
      osimage: "ubuntu-22-clean"
      workertype: "vm"
  kubernetes:
    kubernetestype: "vanilla"
    networkfabric: "flannel"
