---
- hosts: localhost
  become: true
  gather_facts: no

# https://buildvirtual.net/deploy-a-kubernetes-cluster-using-ansible/

  tasks:
     - name: Create containerd config file
       file:
         path: "/etc/modules-load.d/containerd.conf"
         state: "touch"

     - name: Add conf for containerd
       blockinfile:
         path: "/etc/modules-load.d/containerd.conf"
         block: |
               overlay
               br_netfilter

     - name: modprobe
       shell: |
               sudo modprobe overlay
               sudo modprobe br_netfilter


     - name: Set system configurations for Kubernetes networking
       file:
         path: "/etc/sysctl.d/99-kubernetes-cri.conf"
         state: "touch"

     - name: Add conf for containerd
       blockinfile:
         path: "/etc/sysctl.d/99-kubernetes-cri.conf"
         block: |
                net.bridge.bridge-nf-call-iptables = 1
                net.ipv4.ip_forward = 1
                net.bridge.bridge-nf-call-ip6tables = 1

     - name: Apply new settings
       command: sudo sysctl --system

     - name: setting up docker apt repo
       block:
         - name: get docker gpg key
           become: true
           shell:
             cmd: curl https://download.docker.com/linux/ubuntu/gpg > /usr/share/keyrings/docker-archive-keyring-armored.gpg
           #get_url:
           #  url: https://download.docker.com/linux/ubuntu/gpg
           #  dest: /usr/share/keyrings/docker-archive-keyring-armored.gpg
         - name: CMD - process docker key
           become: true
           shell:
             cmd: cat /usr/share/keyrings/docker-archive-keyring-armored.gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
         - name: configure docker apt source
           become: true        
           apt_repository:
             repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable"
             state: present

     - name: install containerd
       shell: |
               # from here https://www.linuxtechi.com/install-kubernetes-on-ubuntu-22-04/
               sudo apt -y update
               sudo apt install -y containerd.io
               sudo containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
               sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
               sudo systemctl restart containerd
               # old containerd commands
               #sudo apt-get update && sudo apt-get install -y containerd
               #sudo mkdir -p /etc/containerd
               #sudo containerd config default | sudo tee /etc/containerd/config.toml
               #sudo systemctl restart containerd

     - name: disable swap
       shell: |
               sudo swapoff -a
               sudo sed -ri '/\sswap\s/s/^#?/#/' /etc/fstab

     - name: install and configure dependencies
       shell: |
               sudo apt-get update && sudo apt-get install -y apt-transport-https curl
               curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

     - name: Create kubernetes repo file
       file:
         path: "/etc/apt/sources.list.d/kubernetes.list"
         state: "touch"

     - name: Add K8s Source
       blockinfile:
         path: "/etc/apt/sources.list.d/kubernetes.list"
         block: |
               deb https://apt.kubernetes.io/ kubernetes-xenial main

     - name: install kubernetes
       shell: |
               sudo apt-get update
               #sudo apt-get install -y kubelet=1.20.1-00 kubeadm=1.20.1-00 kubectl=1.20.1-00
               sudo apt-get install -y kubelet kubeadm kubectl
               sudo apt-mark hold kubelet kubeadm kubectl

