---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: slices.swn.uom.gr
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: swn.uom.gr
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      additionalPrinterColumns:
        #- name: Username
        #  type: string
        #  jsonPath: .spec.credentials.username
        - name: Masters
          type: string
          jsonPath: .spec.infrastructure.masters
        - name: Workers
          type: string
          jsonPath: .spec.infrastructure.workers
        - name: Status
          type: string
          jsonPath: .spec.status
        - name: Output
          type: string
          jsonPath: .spec.output
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                duration:
                  type: string
                usernamespace:
                  type: string
                credentials:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
                infrastructure:
                  type: object
                  properties:
                    masters:
                      type: string
                      default: "0/0"
                    workers:
                      type: string
                      default: "0/0"
                kubernetes:
                  type: object
                  properties:
                    kubernetestype:
                      type: string
                    kubernetesversion:
                       type: string
                    containerdversion:
                       type: string
                    critoolsversion:
                       type: string
                    networkfabric:
                       type: string
                    networkfabricparameters:
                       type: string
                    networkcidr:
                       type: string
                    servicecidr:
                       type: string
                updating:
                  type: boolean
                  default: false
                applications:
                  type: array
                  nullable: true
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      version:
                        type: string
                      parameters:
                        type: string
                      sharefile:
                        type: string
                      waitforfile:
                        type: string
                      scope:
                        type: string
                        enum:
                          - cluster
                          - masters
                          - workers
                          - all
                        default: cluster
                      deployed:
                        type: boolean
                        default: false
                deployment:
                  type: object
                  properties:
                    master:
                      type: array
                      nullable: true
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          ip:
                            type: string
                          mac:
                            type: string
                          secondaryip:
                            type: string
                          secondarymac:
                            type: string
                          resourcetype:
                            type: string
                          osimage:
                            type: string
                          osaccount:
                            type: string
                            default: user
                          serverip:
                            type: string
                          servername:
                            type: string
                          serveroperator:
                            type: string
                    worker:
                      type: array
                      nullable: true
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          ip:
                            type: string
                          mac:
                            type: string
                          secondaryip:
                            type: string
                          secondarymac:
                            type: string
                          resourcetype:
                            type: string
                          osimage:
                            type: string
                          osaccount:
                            type: string
                            default: user
                          serverip:
                            type: string
                          servername:
                            type: string
                          serveroperator:
                            type: string
                status:
                  type: string
                  enum:
                    - defined
                    - allocating_infrastructure
                    - suspended
                    - infrastructure_completed
                    - allocating_applications
                    - allocated
                    - failed
                  default: defined
                output:
                  type: string
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: slices
    # singular name to be used as an alias on the CLI and for display
    singular: slice
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Slice
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - sl
